### ISSUE TITLE
Callback method after upload

### ISSUE THREAD

**Issue by vrt2015** [ogix/ngx-image-uploader#10]
Is it possible to provide a callback method after upload is completed?
Also, is there a way to call an API while removing the image?

**Comment by ogix** [comment]
Hi, yes, there is a (upload) output, and you can get file info.

Sorry, I should add documentation.

**Comment by vrt2015** [comment]
Thanks for the quick reply. 
Is there a way to call an API while removing the image?

**Comment by vrt2015** [comment]
There is a statusChange event emit which is returning the current state of the component. This helped in solving my issue. 
Thanks for the wonderful component - you have thought about every scenario!!!

**Comment by ogix** [comment]
Glad that you figured it out :)
